services:
  openldap-ltb:
    image: openldap-ltb
    container_name: openldap-ltb
    ports:
      - '389:389'
      - '636:636'
    volumes:
      - ./openldap-ltb/schema:/usr/local/openldap/etc/openldap/slapd.d
      - ./openldap-ltb/data:/usr/local/openldap/var/openldap-data
